version: "3.7"
services:
  screenshare:
    image: "${IMAGE_NAME}"
    networks:
        - frontend
    deploy:
      replicas: 1
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.screenshare-frontend.rule=Host(`screenshare.sagacious.dev`)"
        - "traefik.http.routers.screenshare-frontend.entrypoints=websecure"
        - "traefik.http.routers.screenshare-frontend.tls.certresolver=myresolver"
        - "traefik.http.services.screenshare-service.loadbalancer.server.port=8000"