name: Docker Image CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image and publish package
      env:
        VERSION: ${{ date +%s }}
      run: |
        echo $VERSION
        docker build . --file Dockerfile --tag docker.pkg.github.com/utkarsh-pro/screen-share/screenshare:$VERSION
        docker login -u utkarsh-pro -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/utkarsh-pro/screen-share/screenshare:$VERSION
        docker logout docker.pkg.github.com
